#! /bin/sh

picom &
polybar &
~/.fehbg &
setxkbmap us -variant dvorak &
xsetroot -cursor_name left_ptr &


pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill /home/z1/wallpapers

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         5
bspc config window_gap          12
bspc config focused_border_color	'#6272a4'
bspc config active_border_color		'#6272a4'
bspc config normal_border_color 	'#44475a'	


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc rule -a kitty desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
